### PR TITLE
Updated text in footer

### PR DESCRIPTION
**Pull request by michaelpande**

### CODE REVIEW

**Comment by michaelpande** [comment]
This is what it should look like now: 
image

**Review by MikaelNordberg — DISMISSED** [review]
Looks good

**Comment by SjurSutterudSagen** [comment]
Currently, we have a problem with how the checks on PRs are enforced. It requires the Chromatic checks, even on PRs that don't need to build chromatic. A workaround until we fix the issue is to add/remove a blank line/space in a Readme.md file inside the "libs/pxweb2-ui/**" folder.

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Pull request merged**
