### PR TITLE
PXWEB2-34 Added option for icon left and icon right. Added stories.

### PR DESCRIPTION
**Pull request by PerIngeVaaje**
Changed display from inline-felx to flex for .medium class

### CODE REVIEW

**Comment by PerIngeVaaje** [comment]
Did a rebase to get latest changes from main after nx updating process. Only changes done in Button-folder as part of this pr.

**Review by SjurSutterudSagen — APPROVED** [review]
LGTM

**Review by SjurSutterudSagen — DISMISSED** [review]
Still good

**Review by SjurSutterudSagen — DISMISSED** [review]
Can I approve now?

**Review by MikaelNordberg — DISMISSED** [review]
Looks good

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Pull request merged**
