### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by likp**
Have updated the readme you could have a look at it at

https://github.com/PxTools/PxWeb2/tree/fix/readme?tab=readme-ov-file

### CODE REVIEW

**Comment by AsaArrhen** [comment]
En mening är inte avslutad. Autom... var felstavat

**Comment by likp** [comment]
@AsaArrhen the error should be fixed now.

**Comment by AsaArrhen** [comment]
> @AsaArrhen the error should be fixed now.

@likp Hittade ett till stavfel Right **no** we are working hard on the new version of PxWeb 2.  **now**

**Comment by likp** [comment]
@AsaArrhen I hope it would be fix now :-)

**Review by AsaArrhen — APPROVED** [review]
Now it lokks fine @likp

**Pull request merged**
